alexcasalboni/aws-lambda-power-tuning

- serverless.base.yml
No code change is needed.
Fix #13
> Update runtime to nodejs8.10

- lambda/utils.js
- package.json
- test/test-utils.js
> Fixed cross-region access

- execute.sh
- sample-execution-input.json
- template.yml
Implements #3 
It's a simple bash script to avoid using the web console.
> State machine execution command

- template.yml
> Least-privilege IAM permissions to each function (actions)

- lambda/finalizer.js
- test/test-lambda.js
Implements #31 
Will add documentation in another PR.
> Multiple strategies

- template.yml
> Updated function runtime to nodejs10.x

- lambda/initializer.js
- lambda/utils.js
- template.yml
- test/test-lambda.js
- test/test-utils.js
Fix #36 
This improvement will make sure the `$LATEST` version is reset to the original memory configuration.
> Reset $LATEST memory configuration

- lambda/executor.js
- test/test-lambda.js
Implements #37 
TODO: update documentation.
> Implement weighted payloads

- lambda/optimizer.js
- scripts/deploy-sar-app.sh
- scripts/deploy.sh
- test/test-lambda.js
> Bugfix: optimizer with dry-run shouldn't try to validate input

- README-SAR.md
- README.md
I have updated into the document expression of the state machine output cost
I think It is easier reading for me not to use floating-point expressions.
> Fix document the cost number

- README-SAR.md
- README.md
- lambda/executor.js
- test/test-lambda.js
Cover a new case encountered in #85 
TODO:
> Add new test to cover count(payloads) > num case

- .mocharc.js
- .nycrc.json
- package.json
- template.yml
- test/setup.spec.js
- test/unit/test-lambda.js
- test/unit/test-utils.js
Starting of introducing test-suite to project.
Test-suite: sinon.
If this is a **good** choice, then the next step will be to introduce **chai**, and **chai-as-Promise**, followed by building out the tests accordingly.
> Testsuite addition

- README-SAR.md
- README.md
- lambda/executor.js
- lambda/utils.js
- test/test-lambda.js
- test/test-utils.js
- test/unit/test-lambda.js
> Implement pre/post-processing functions logic

- test/unit/test-lambda.js
- test/unit/test-utils.js
Completes #2 and #79 🚀 
FYI @gino247
> Refactor utils test with sinon

- lambda/utils.js
- test/unit/test-utils.js
Fix #97 (again)
#98 did not cover all possible cases, sorry 🙏
> Bugfix (2): weighted payload allocation

- lambda/executor.js
- lambda/utils.js
- test/unit/test-lambda.js
> Bugfix: include processed payload log in case of failed invocation

- scripts/deploy-sar-app.sh
- scripts/deploy.sh
- scripts/execute.sh
These commits add the bash shebang allowing to execute the scripts without guessing the right interpreter.
> Adds shebang to scripts

- README-INPUT-OUTPUT.md
- template.yml
> Add permissionsBoundary parameter, applied to all functions

- template.yml
> bugfix: apply permissions boundary to Step Functions tole too

- README-DEPLOY.md
Quick question -- do you have documentation of the SAR template items somewhere? I wanted to update those too.
> Add Terraform deployment instructions!

- .travis.yml
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
> Add NodeJS 15 and 16 to Travis

- lambda/utils.js
- test/unit/test-utils.js
> Bugfix: string payload

- template.yml
My organization enforces naming pattern for resources.
This pull request would allow me to use the cfn template as is (via sam).
Thank you.
> Allow to customize sdk layer name

- template.yml
- terraform/module/lambda.tf
https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#211340
> Bump tf and layer to nodejs16.x

- template.yml
- terraform/module/json_files/state_machine.json
This PR is to replace the Parameters with ItemSelector inside to State Machine Branching, like [documentation](https://docs.aws.amazon.com/step-functions/latest/dg/input-output-itemselector.html) recommend to us
> Replacing Parameters field with ItemSelector

- lambda/utils.js
- test/unit/test-utils.js
> Support JSON logging

- .gitignore
- README-DEPLOY.md
- README-EXECUTE.md
- README-INPUT-OUTPUT.md
- README.md
- terraform/Readme.md
* Updated main readme for deploy instructions
* Removed references to the UI and Lumigo
* Minor other edits.
> Deployment instruction revisions, removed references to UI and Lumigo

- README-DEPLOY.md
Updated the documentation for CDK using v2 instead of v1
> update doc with CDK v2
