- README.md
- lambda/executor.js
- lambda/finalizer.js
- lambda/utils.js
- statemachine/template-branch.json
- test/test-lambda.js
- test/test-utils.js
I have been using and enjoy the tool and cost is a big consideration when picking a POWER for lambda, but SLA's are also important, so I wanted to display both cost and duration in the results. The finalizer still orders and suggests the result from price only.
> Result set show cost and duration

- README.md
- lambda/initializer.js
- serverless.base.yml
Found that when running with 4 or less invocation, no results are displayed partly because of the 20% outlier filtering. It took me a while to realize this so it might be good to make this a bit more clear. Also I found that my serverless version did not accept the base.yml file, found the fix in the issues forum but no pull request yet. 
Let me know if there are any issues with this pull request.
> Add minimum number of invokes, fix base.yml for some serverless versions

- .travis.yml
- serverless.base.yml
As suggested in #11 
There is no noticeable impact on the state machine performance, and it's always possible to raise it for specific edge cases.
> Lowered memory to 128MB

- lambda/executor.js
- template.yml
- test/test-lambda.js
I have added specific check to intercept failed executions.
Note: invocation errors just return 200 and come with a `FunctionError` and `Payload` with error information.
> Retry policies & failed invocations

- .eslintrc.json
- README-SAR.md
- README.md
- lambda/executor.js
- lambda/finalizer.js
- lambda/utils.js
- package.json
- template.yml
- test/test-lambda.js
- test/test-utils.js
Implements #33 
The new state machine output looks as follows:
```json
{
"results": {
"power": "128",
"cost": 2.08e-7,
"duration": 2.9066666666666667,
"stateMachine": {
"executionCost": 0.00045,
"lambdaCost": 0.0005252
}
}
}
```
Note: this is a breaking change in the state machine output (the previous output was a list of two objects, resulting from the parallel state [Finalizer + Cleaner]).
What I've implemented?
- new `Success` status to re-map the `Finalizer` output properly
- new `stateMachine` output, containing `executionCost` (Step Functions cost) and `lambdaCost` (Lambda cost)
> Added overall execution cost information (state machine output)

- lambda/finalizer.js
- lambda/utils.js
- template.yml
- test/test-lambda.js
- test/test-utils.js
Implements #40 
New state machine output:
```json
{
"results": {
"power": "1024",
"cost": 0.000064896,
"duration": 3890.8916666666664,
"stateMachine": {
"executionCost": 0.00045,
"lambdaCost": 0.00455936,
"visualization": "https://lambda-power-tuning.show/#gAAAAQACAAQABsAL;ZooQR4yvkUa/pQRGRC5zRaADHUVjOftE;QdWhOEMkoziDT5Q4xhiIOMYYiDi6RNc4"
}
}
}
```
The visualization URL will allow users to visualize and inspect statistics in an external web app. 
Notes:
- no data is actually sent to the visualization web app (URL hash stays in the browser)
- documentation to be added
- the webapp repo is [here](https://github.com/alexcasalboni/aws-lambda-power-tuning-ui) (it's a fork)
> Add visualization URL to state machine output

- README-SAR.md
- README.md
- deploy.sh
- sample-execution-input.json
- template.yml
Implements #52 
New CloudFormation parameter named `lambdaResource`.
The default value is still `*`, but it can be customized at deploy-time.
Goal: reduce blast radius and provide an easy way to follow least-privilege best practice.
> Implement new lambdaResource CFN parameter

- lambda/analyzer.js
- test/test-lambda.js
Fix #60 
- when same optimal speed, pick the cheapest
- when same optimal cost, pick the fastest
> Improve optimal selection when same speed/cost is detected

- lambda/analyzer.js
- lambda/executor.js
- lambda/optimizer.js
- test/test-lambda.js
Implement #41 
The new `dryRun` option allows you to verify that permissions and input function are correctly configured.
It will run the input function only once (independently of the value of `num`).
It also disable logs analysis and auto-optimization logic.
> Implement dryRun option

- README.md
I have added into the readme the quickest way to deploy the power tuning state machine with AWS CDK.
> update readme to show deploying with cdk

- lambda/executor.js
- lambda/utils.js
- template.yml
- test/unit/test-lambda.js
The bug exists since we merged #47 (version `3.0.0`).
Because of the manual mapping of the Executor input parameters, some optional parameters became mandatory otherwise Step Function would fail.
With this fix, we allow for these optional parameters to not exist in the original input and we also avoid the manual mapping of every parameter needed by the Executor function. This will make it easier to use new parameters in the future too.
> Bugfix: optional mapping for Executor input (map)

- lambda/executor.js
- lambda/utils.js
- package-lock.json
- package.json
- test/unit/test-lambda.js
- test/unit/test-utils.js
Fix #97 
The bug wasn't covered by the test suite and it only happened in the case of an uneven division between `num` and `count(payloads)` (e.g. `num=100` and `count(payloads)=3`).
Solution: just make sure the array of generated payloads is filled until the end, using the last payload value.
> Bugfix: weighted payload allocation (uneven division)

- scripts/deploy.sh
So users do not need to touch the code. Code and configurations should be separated, IMHO.
> Fall back parameters to environment variables

- .travis.yml
https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-node-js-runtimes-10-x-in-the-aws-sdk-for-javascript-v2/
> Add NodeJS 13 and 14 to Travis

- lambda/initializer.js
- lambda/utils.js
- package.json
- template.yml
- test/unit/test-lambda.js
- test/unit/test-utils.js
Implements #134 
The initialize function now waits for the update to be completed with `lambda.waitFor('functionUpdated')` after invoking `lambda.updateFunctionConfiguration`.
It works for all functions (opt-in and opt-out).
> Implement function update waiter (states expansion)

- .gitignore
- README-DEPLOY.md
- layer-sdk/build.sh
- layer-sdk/package-lock.json
- layer-sdk/package.json
- package-lock.json
- package.json
- scripts/build-layer.sh
- template.yml
This allows more granular control over the SDK versions in the future, to avoid unexpected incompatibilities and to support new services/features that aren't immediately available in the runtime SDK.
> Add explicit SDK dependency as Lambda Layer

- lambda/utils.js
- test/unit/test-utils.js
By default sort() is ordering items alphabetically. This was causing some unexpected results when comparing when some cold start durations where ignored for one configuration and preserved for another.
> Sort durations numerically

- terraform/main.tf
- terraform/variables.tf
It's been reported to me that the region is still set in the calling module but it's been removed from the main module. This PR fixes that issue
> Resolving issue with region being passed into a module that doesn't expect it

- template.yml
This pull request is used to set a retention value for log groups (other than never expired).
Also, because log groups are defined as resources in CFN, tags from SAM are applied to log groups.
> Add log groups with retention value

- lambda/executor.js
- lambda/utils.js
- package-lock.json
- test/unit/test-lambda.js
- test/unit/test-utils.js
I noticed when benchmarking Lambda's new [SnapStart](https://docs.aws.amazon.com/lambda/latest/dg/snapstart.html) feature that aliases take awhile to become active.  Without this change the executor step would fail due to something along the lines of "invalid function state pending".  In my testing it takes upwards of 2 minutes for a power factor alias to become active when SnapStart is enabled.  I'm guessing this is because Lambda needs to take a VM snapshot of every new execution-environment (power factor).
I tested this with unit tests and empirically against a SnapStart enabled Lambda function.
> add waiter to executor to make sure Alias is active

- template.yml
- terraform/module/json_files/optimizer.json
Lack of this Action (`lambda:GetFunctionConfiguration`) doesn't allow to use `"autoOptimize": true` in CI pipeline. 
The Optimizer is not allowed to retrieve the Lambda config, and thus it can not change the Lambda parameters:
`
User: [serverlessrepo-aws-lambda-power-tuni-optimizerRole ARN] is not authorized to perform: lambda:GetFunctionConfiguration on resource: [lambda ARN] because no identity-based policy allows the lambda:GetFunctionConfiguration action
`
The error in Step Functions looks like this:
> Allow GetFunctionConfiguration action for Optimizer function (autoOptimize)

- .github/workflows/tests-integration.yml
- .github/workflows/tests.yml
- template.yml
- terraform/module/lambda.tf
Fixes: #221 
This PR switches NodeJS Version from v16 to v20. 
Two additional changes came from me using an Editor which adds a newline on save.
> Updating lambda functions to nodejs 20

- lambda/cleaner.js
- lambda/executor.js
- lambda/utils.js
- layer-sdk/package-lock.json
- layer-sdk/package.json
- package-lock.json
- package.json
- template.yml
- terraform/module/lambda.tf
- test/unit/test-lambda.js
- test/unit/test-utils.js
This is a follow up PR of #222 and migrates aws sdk v2 to aws sdk v3. It also contains the commit from #222 and should only be merged afterwards.
> Migrate sdk v2 to sdk v3

- cdk/README.md
- cdk/python/README.md
- cdk/python/app.py
- cdk/python/app/lambdapowertuner_stack.py
- cdk/python/cdk.json
- cdk/python/requirements.txt
- cdk/python/source.bat
- cdk/python/tests/unit/test_lambdapowertuner_stack.py
> Added python cdk

- README-INPUT-OUTPUT.md
- lambda/utils.js
- test/unit/test-utils.js
Addresses https://github.com/alexcasalboni/aws-lambda-power-tuning/issues/226
Checks if payload is "correctly" weighted and then creates the weighted payloads. Otherwise treated as an array-shaped payload.
Added unit tests.
Attached one weighted SFN execution and one unweighted.
Weighted payload to Lambda:
Unweighted payload to Lambda:
[weighted_execution.json](https://github.com/alexcasalboni/aws-lambda-power-tuning/files/14745897/weighted_execution.json)
[unweighted_execution.json](https://github.com/alexcasalboni/aws-lambda-power-tuning/files/14745898/unweighted_execution.json)
> 226: support for array-shaped payloads

- statemachine/statemachine.asl.json
- template.yml
Externalized the ASL definition for the statemachine to a separate JSON file
- used AWS::Serverless::StateMachine to do this.
> Externalize ASL as JSON file

- lambda/executor.js
- lambda/utils.js
- test/unit/test-lambda.js
- test/unit/test-utils.js
Error type, message and trace will be shown for function invocation errors. Also when happens for pre or post processing.
Examples for executor function response
- Raising an exception in the function code:
```
{
"errorType": "Error",
"errorMessage": "Invocation error (running in series) with payload \"null\" - original error type: \"Exception\", original error message: \"Exception raised during execution.\", trace: \"  File \"/var/task/lambda_function.py\", line 9, in lambda_handler\n    raise Exception(\"Exception raised during execution.\")\n\"",
"trace": [
"Error: Invocation error (running in series) with payload \"null\" - original error type: \"Exception\", original error message: \"Exception raised during execution.\", trace: \"  File \"/var/task/lambda_function.py\", line 9, in …
```
> Show error message and type on function invocation errors

- cdk/typescript/README.md
The typesscript readme instructions for deploying the stack seems to be missing a word
> fix(docs): update the typescript deploy commands
